# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B4flMCAigrXocq6e18V_hPpNSnfnVcE7
"""

from google.colab import drive;
drive.mount('/content/drive')

!unzip "/content/drive/MyDrive/Archive.zip"

from tensorflow.keras.preprocessing.image import ImageDataGenerator

# Dimensions for resizing
img_width, img_height = 150, 150
batch_size = 32

train_datagen = ImageDataGenerator(
    rescale=1./255,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True
)

test_val_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory(
    'train/', target_size=(img_width, img_height),
    batch_size=batch_size, class_mode='binary')

val_generator = test_val_datagen.flow_from_directory(
    'val/', target_size=(img_width, img_height),
    batch_size=batch_size, class_mode='binary')

test_generator = test_val_datagen.flow_from_directory(
    'test/', target_size=(img_width, img_height),
    batch_size=batch_size, class_mode='binary')

from tensorflow.keras import layers, models

model = models.Sequential([
    layers.Conv2D(32, (3, 3), activation='relu', input_shape=(img_width, img_height, 3)),
    layers.MaxPooling2D(2, 2),

    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D(2, 2),

    layers.Conv2D(128, (3, 3), activation='relu'),
    layers.MaxPooling2D(2, 2),

    layers.Flatten(),
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.5),
    layers.Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
history = model.fit(
    train_generator,
    steps_per_epoch=train_generator.samples // batch_size,
    epochs=10,
    validation_data=val_generator,
    validation_steps=val_generator.samples // batch_size
)

test_loss, test_acc = model.evaluate(test_generator)
print(f"Test Accuracy: {test_acc*100:.2f}%")

from sklearn.metrics import classification_report, confusion_matrix
import numpy as np

# Predict the test set
Y_pred = model.predict(test_generator)
y_pred = np.round(Y_pred) # Convert probabilities to 0 or 1

print(classification_report(test_generator.classes, y_pred, target_names=['Normal', 'Pneumonia']))

model.save('pneumonia_detection_model.h5')